(()=>{
const G=window.EVO,{rnd,pick,clamp,angleDiff}=G;
class Food{
 constructor(x=rnd(40,G.WORLD.w-40),y=rnd(40,G.WORLD.h-40),v=rnd(2,7),c=pick(['#86ffe1','#72e9ff','#ffdf7a','#ff91c8','#c39bff','#baff7f'])){Object.assign(this,{x,y,v,c,r:3+Math.sqrt(v),dead:false})}
 draw(){const p=G.screen(this.x,this.y),r=this.r*G.camera.z;if(p.x<-20||p.x>G.vw+20||p.y<-20||p.y>G.vh+20)return;G.ctx.save();G.ctx.globalCompositeOperation='lighter';const g=G.ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r*2.8);g.addColorStop(0,'#fff');g.addColorStop(.3,this.c);g.addColorStop(1,'transparent');G.ctx.fillStyle=g;G.ctx.beginPath();G.ctx.arc(p.x,p.y,r*2.8,0,G.TAU);G.ctx.fill();G.ctx.restore()}
}
class Snake{
 constructor({ai=false,name='小团子',score=80,x=rnd(300,G.WORLD.w-300),y=rnd(300,G.WORLD.h-300),palette=pick(G.palettes),style=pick(G.botStyles)}={}){Object.assign(this,{ai,name,score,x,y,palette,style,a:rnd(0,G.TAU),ta:0,dead:false,body:[],mag:28,speed:1,boost:1,turn:1,feast:1,orbiters:0,boostCost:1,buffs:[],inv:.8,think:0,target:null,boosting:false,kills:0,trail:0,fins:0,killBonus:0});this.ta=this.a;for(let i=0;i<36;i++)this.body.push({x:x-i*6,y})}
 get stage(){return G.stageFor(this)}get radius(){return this.stage[2]}get maxBody(){return 30+Math.floor(Math.sqrt(this.score)*2.55)}
 update(dt){if(this.dead)return;this.inv=Math.max(0,this.inv-dt);if(this.ai)this.brain(dt);const turn=2.6*this.turn*dt;this.a+=clamp(angleDiff(this.a,this.ta),-turn,turn);const boosting=this.boosting&&this.score>55;const v=(102+Math.min(27,Math.sqrt(this.score)*.6))*this.speed*(boosting?1.6*this.boost:1);this.x+=Math.cos(this.a)*v*dt;this.y+=Math.sin(this.a)*v*dt;if(this.x<45||this.x>G.WORLD.w-45||this.y<45||this.y>G.WORLD.h-45)this.ta=Math.atan2(G.WORLD.h/2-this.y,G.WORLD.w/2-this.x);this.x=clamp(this.x,10,G.WORLD.w-10);this.y=clamp(this.y,10,G.WORLD.h-10);const h=this.body[0];if(Math.hypot(this.x-h.x,this.y-h.y)>5.5)this.body.unshift({x:this.x,y:this.y});while(this.body.length>this.maxBody)this.body.pop();if(boosting)this.score=Math.max(50,this.score-dt*9*this.boostCost);this.eatFood();if(this.inv<=0)this.checkCollision()}
 brain(dt){this.think-=dt;if(this.think<=0){this.think=rnd(.22,.62);if(this.style==='猎手型'){const prey=G.snakes.filter(s=>s!==this&&!s.dead&&s.inv<=0).sort((a,b)=>Math.hypot(this.x-a.x,this.y-a.y)-Math.hypot(this.x-b.x,this.y-b.y))[0];this.target=prey&&Math.hypot(this.x-prey.x,this.y-prey.y)<620?prey:pick(G.foods);this.boosting=Math.random()<.16}else if(this.style==='游荡型'){this.target=Math.random()<.55?pick(G.foods):{x:rnd(180,G.WORLD.w-180),y:rnd(180,G.WORLD.h-180)};this.boosting=Math.random()<.09}else{this.target=pick(G.foods);this.boosting=Math.random()<.04}}
 let tx=this.target?.x||G.WORLD.w/2,ty=this.target?.y||G.WORLD.h/2,ax=0,ay=0;if(this.target instanceof Snake){tx+=Math.cos(this.target.a)*70;ty+=Math.sin(this.target.a)*70}for(const s of G.snakes){if(s===this||s.dead)continue;for(let i=7;i<s.body.length;i+=8){const q=s.body[i],dx=this.x-q.x,dy=this.y-q.y,d=Math.hypot(dx,dy);if(d<125){ax+=dx/(d*d+1)*7200;ay+=dy/(d*d+1)*7200}}}this.ta=Math.atan2(ty-this.y+ay,tx-this.x+ax)+rnd(-.035,.035)}
 eatFood(){const R=this.radius+this.mag;for(const f of G.foods){if(f.dead)continue;let dx=this.x-f.x,dy=this.y-f.y,d=Math.hypot(dx,dy);if(d<R&&d>3){const q=(1-d/R)*.16;f.x+=dx*q;f.y+=dy*q}if(d<this.radius+f.r+3){f.dead=true;this.score+=f.v*this.feast;G.burst(f.x,f.y,f.c,4)}}if(this.orbiters)for(let k=0;k<this.orbiters;k++){const a=G.time*1.8+k*G.TAU/this.orbiters,ox=this.x+Math.cos(a)*(this.radius+28),oy=this.y+Math.sin(a)*(this.radius+28);for(const f of G.foods)if(!f.dead&&Math.hypot(f.x-ox,f.y-oy)<17){f.dead=true;this.score+=f.v*this.feast*.8}}}
 checkCollision(){for(const other of G.snakes){if(other===this||other.dead||other.inv>0)continue;const hd=Math.hypot(this.x-other.x,this.y-other.y);if(hd<(this.radius+other.radius)*.72){this.die(other);other.die(this);return}for(let i=6;i<other.body.length;i+=2){const p=other.body[i];if(Math.hypot(this.x-p.x,this.y-p.y)<this.radius*.72+other.radius*.68){this.die(other);return}}}}
 die(killer){if(this.dead)return;this.dead=true;for(let i=0;i<this.body.length;i+=2){const p=this.body[i];G.foods.push(new Food(p.x+rnd(-5,5),p.y+rnd(-5,5),rnd(3,8),this.palette[i%2]))}G.burst(this.x,this.y,this.palette[0],18);if(killer&&killer!==this){killer.kills++;killer.score+=20+(killer.killBonus||0);G.onKill?.(killer,this)}if(this===G.player)setTimeout(G.gameOver,360)}
}
G.Food=Food;G.Snake=Snake;
})();