(()=>{
const G=window.EVO,segCache=new Map(),foodCache=new Map();
const skinOf=s=>s.skin||{id:'legacy',name:'经典蛇',icon:'🐍',palette:s.palette,motif:'scales',shape:'round'};
function poly(x,cx,cy,r,n,rot=0){x.beginPath();for(let i=0;i<n;i++){const a=rot+i*G.TAU/n,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath()}
function star(x,cx,cy,r,n=4){x.beginPath();for(let i=0;i<n*2;i++){const a=-Math.PI/2+i*Math.PI/n,q=i%2?r:r*.34,px=cx+Math.cos(a)*q,py=cy+Math.sin(a)*q;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath()}
function stageDecor(x,skin,lv,v){const p=skin.palette,cx=36,cy=36;x.save();
 if(lv>=1){x.fillStyle=p[0]+'b8';for(const sy of [-1,1]){x.beginPath();x.moveTo(cx-8,cy+sy*18);x.quadraticCurveTo(cx-22,cy+sy*(25+lv*1.4),cx+2,cy+sy*20);x.closePath();x.fill()}}
 if(lv>=2&&v%2===0){x.fillStyle=p[2]+'d0';for(const sy of [-1,1]){x.beginPath();x.moveTo(cx+2,cy+sy*18);x.lineTo(cx-4,cy+sy*(27+lv));x.lineTo(cx+9,cy+sy*20);x.closePath();x.fill()}}
 if(lv>=3){x.strokeStyle='#ffffff55';x.lineWidth=1.5;x.beginPath();x.arc(cx,cy,27,0,G.TAU);x.stroke()}
 if(lv>=4&&v%2){x.fillStyle=p[0]+'ce';for(let k=0;k<4;k++){const a=k*Math.PI/2+.2;x.beginPath();x.moveTo(cx+Math.cos(a-.18)*22,cy+Math.sin(a-.18)*22);x.lineTo(cx+Math.cos(a)*(31+lv),cy+Math.sin(a)*(31+lv));x.lineTo(cx+Math.cos(a+.18)*22,cy+Math.sin(a+.18)*22);x.closePath();x.fill()}}
 if(lv>=5){x.strokeStyle=p[0]+'8f';x.lineWidth=3;for(const sy of [-1,1]){x.beginPath();x.arc(cx,cy+sy*5,27,sy>0?.15:Math.PI+.15,sy>0?Math.PI-.15:G.TAU-.15);x.stroke()}}
 if(lv>=6&&v%2===0){x.fillStyle=p[0]+'9c';for(const sy of [-1,1]){x.beginPath();x.moveTo(cx-5,cy+sy*17);x.quadraticCurveTo(cx-30,cy+sy*(37+lv),cx-15,cy+sy*6);x.quadraticCurveTo(cx-28,cy+sy*17,cx-5,cy+sy*17);x.fill()}}
 if(lv>=7){x.fillStyle='#eaffffd0';for(let k=0;k<6;k++){const a=k*G.TAU/6+(v?.18:0);x.beginPath();x.moveTo(cx+Math.cos(a-.13)*24,cy+Math.sin(a-.13)*24);x.lineTo(cx+Math.cos(a)*(31+lv*.8),cy+Math.sin(a)*(31+lv*.8));x.lineTo(cx+Math.cos(a+.13)*24,cy+Math.sin(a+.13)*24);x.closePath();x.fill()}}
 if(lv>=8){x.strokeStyle='#fff1a8b8';x.lineWidth=1.8;x.beginPath();x.ellipse(cx,cy,33,23,.2,0,G.TAU);x.stroke();if(v%2===0){x.fillStyle='#fff6bd';for(let k=0;k<3;k++){const a=k*G.TAU/3+.3;star(x,cx+Math.cos(a)*31,cy+Math.sin(a)*22,3.4);x.fill()}}}
 if(lv>=9){x.strokeStyle='#b8f7ffb8';x.lineWidth=1.5;x.beginPath();x.ellipse(cx,cy,37,18,-.22,0,G.TAU);x.stroke()}
 x.restore()}
function baseShape(x,skin){const p=skin.palette,g=x.createRadialGradient(27,24,2,36,36,27);g.addColorStop(0,'#fff');g.addColorStop(.18,p[0]);g.addColorStop(.68,p[1]);g.addColorStop(1,p[2]);x.fillStyle=g;
 switch(skin.shape){case'crystal':poly(x,36,36,25,6,Math.PI/6);x.fill();break;case'mech':poly(x,36,36,25,8,Math.PI/8);x.fill();break;case'cloud':for(const q of [[-10,3,16],[6,-4,18],[15,6,13]]){x.beginPath();x.arc(36+q[0],36+q[1],q[2],0,G.TAU);x.fill()}break;case'bone':x.beginPath();x.ellipse(36,36,27,17,0,0,G.TAU);x.fill();break;case'scale':x.beginPath();x.ellipse(36,36,27,23,0,0,G.TAU);x.fill();break;default:x.beginPath();x.arc(36,36,25,0,G.TAU);x.fill()}}
function motif(x,skin,v){const m=skin.motif;x.save();x.translate(36,36);x.globalAlpha=.9;
 if(m==='emoji'||m==='icon'){x.globalAlpha=1;x.font='23px "Apple Color Emoji","Segoe UI Emoji",sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(skin.icon,0,1)}
 else if(m==='scales'||m==='dragon'){x.strokeStyle='#ffffff60';x.lineWidth=1.5;for(let yy=-12;yy<=12;yy+=10)for(let xx=-12;xx<=12;xx+=12){x.beginPath();x.arc(xx+(yy%20?6:0),yy,6,0,Math.PI);x.stroke()}}
 else if(m==='circuit'){x.strokeStyle='#8affff';x.lineWidth=1.6;x.beginPath();x.moveTo(-15,-8);x.lineTo(-3,-8);x.lineTo(-3,7);x.lineTo(13,7);x.moveTo(3,-16);x.lineTo(3,-1);x.lineTo(16,-1);x.stroke()}
 else if(m==='bone'){x.strokeStyle='#777c91';x.lineWidth=4;x.beginPath();x.moveTo(-14,0);x.lineTo(14,0);x.stroke();for(const q of [-15,15]){x.fillStyle='#fffce9';x.beginPath();x.arc(q,-4,5,0,G.TAU);x.arc(q,4,5,0,G.TAU);x.fill()}}
 else if(m==='bubble'){x.strokeStyle='#fff9';x.lineWidth=1.5;for(const q of [[-9,-7,5],[8,6,7],[11,-10,3]]){x.beginPath();x.arc(q[0],q[1],q[2],0,G.TAU);x.stroke()}}
 else if(m==='flame'){x.fillStyle='#fff0a8';x.beginPath();x.moveTo(-4,14);x.quadraticCurveTo(-13,2,-2,-15);x.quadraticCurveTo(2,-3,10,-12);x.quadraticCurveTo(13,6,4,14);x.fill()}
 else if(m==='coral'){x.strokeStyle='#ffe1fa';x.lineWidth=2.5;x.beginPath();x.moveTo(0,15);x.lineTo(0,-14);x.moveTo(0,-4);x.lineTo(-10,-11);x.moveTo(1,3);x.lineTo(11,-6);x.stroke()}
 else if(m==='stripe'){x.strokeStyle='#fff8';x.lineWidth=5;for(let q=-16;q<=16;q+=11){x.beginPath();x.moveTo(q-6,-18);x.lineTo(q+6,18);x.stroke()}}
 else if(m==='star'){x.fillStyle='#fff9';star(x,0,0,11,5);x.fill()}
 else if(m==='gem'){x.strokeStyle='#fff9';x.lineWidth=1.8;poly(x,0,0,18,6,Math.PI/6);x.stroke();x.beginPath();x.moveTo(-15,-9);x.lineTo(0,0);x.lineTo(15,-9);x.moveTo(0,0);x.lineTo(0,18);x.stroke()}
 else if(m==='cat'){x.fillStyle='#925565';x.beginPath();x.arc(0,4,6,0,G.TAU);x.fill();for(const q of [[-7,-6],[0,-9],[7,-6]]){x.beginPath();x.arc(q[0],q[1],3.5,0,G.TAU);x.fill()}}
 else if(m==='spots'){x.fillStyle='#3f845d99';for(const q of [[-9,-7,5],[8,-4,4],[1,10,6]]){x.beginPath();x.arc(q[0],q[1],q[2],0,G.TAU);x.fill()}}
 else if(['strawberry','grape','banana','watermelon','pineapple','fruitmix'].includes(m)){x.globalAlpha=1;x.font='21px "Apple Color Emoji","Segoe UI Emoji",sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(skin.icon,0,1)}
 x.restore()}
function makeSegment(skin,lv,v){const key=`${skin.id}|${lv}|${v&1}`;if(segCache.has(key))return segCache.get(key);const c=document.createElement('canvas');c.width=c.height=72;const x=c.getContext('2d');stageDecor(x,skin,lv,v);baseShape(x,skin);motif(x,skin,v);x.fillStyle='#ffffff35';x.beginPath();x.ellipse(29,27,6,2.5,-.5,0,G.TAU);x.fill();segCache.set(key,c);return c}
function makeFood(color){if(foodCache.has(color))return foodCache.get(color);const c=document.createElement('canvas');c.width=c.height=36;const x=c.getContext('2d'),g=x.createRadialGradient(18,18,0,18,18,17);g.addColorStop(0,'#fff');g.addColorStop(.18,color);g.addColorStop(.52,color+'cc');g.addColorStop(1,'transparent');x.fillStyle=g;x.beginPath();x.arc(18,18,17,0,G.TAU);x.fill();x.fillStyle='#fff';star(x,18,18,8,4);x.fill();foodCache.set(color,c);return c}
G.drawFoodSprite=f=>{const p=G.screen(f.x,f.y),r=f.r*G.camera.z;if(p.x<-24||p.x>G.vw+24||p.y<-24||p.y>G.vh+24)return;const s=Math.max(10,r*5.6);G.ctx.drawImage(makeFood(f.c),p.x-s/2,p.y-s/2,s,s)};
function bodyPoint(s,phase){const n=s.body.length;if(!n)return{x:s.x,y:s.y};const t=((phase%1)+1)%1,i=Math.min(n-1,Math.floor(t*n));return s.body[i]||{x:s.x,y:s.y}}
function buffFx(s){if(!s.buffs?.length)return;const X=G.ctx,z=G.camera.z,r=s.radius*z;X.save();X.globalCompositeOperation='lighter';for(let i=0;i<s.buffs.length;i++){const key=s.buffs[i][5],q=bodyPoint(s,G.time*(.06+(i%3)*.012)+i*.173),p=G.screen(q.x,q.y),a=G.time*(1.8+i*.09)+i;if(p.x<-50||p.x>G.vw+50||p.y<-50||p.y>G.vh+50)continue;X.lineWidth=Math.max(1,1.5*z);X.shadowBlur=8;
  if(key==='magnet'){X.strokeStyle='#64f6ffbb';X.shadowColor='#64f6ff';X.beginPath();X.arc(p.x,p.y,r+8+Math.sin(a)*5,0,G.TAU);X.stroke()}
  else if(key==='speed'){X.strokeStyle='#ffe46f';X.shadowColor='#ffe46f';for(let k=0;k<3;k++){const aa=a+k*2.1;X.beginPath();X.moveTo(p.x+Math.cos(aa)*4,p.y+Math.sin(aa)*4);X.lineTo(p.x+Math.cos(aa)*18,p.y+Math.sin(aa)*18);X.stroke()}}
  else if(key==='feast'){X.fillStyle='#ff8ab8';X.shadowColor='#ff6fae';for(let k=0;k<3;k++){const aa=a+k*G.TAU/3;X.beginPath();X.arc(p.x+Math.cos(aa)*(r+9),p.y+Math.sin(aa)*(r+9),2.2+k*.4,0,G.TAU);X.fill()}}
  else if(key==='turn'){X.strokeStyle='#eaffffcc';X.shadowColor='#dff';X.beginPath();X.arc(p.x,p.y,r+10,a,a+1.2);X.stroke();X.beginPath();X.arc(p.x,p.y,r+15,a+Math.PI,a+Math.PI+1);X.stroke()}
  else if(key==='spore'){X.fillStyle='#c69cff';X.shadowColor='#b36cff';for(let k=0;k<2;k++){const aa=a+k*Math.PI;X.beginPath();X.arc(p.x+Math.cos(aa)*(r+13),p.y+Math.sin(aa)*(r+13),4,0,G.TAU);X.fill()}}
  else if(key==='comet'){X.strokeStyle='#78bfffcc';X.shadowColor='#5fb0ff';X.beginPath();X.moveTo(p.x-18*Math.cos(s.a),p.y-18*Math.sin(s.a));X.lineTo(p.x+8*Math.cos(s.a),p.y+8*Math.sin(s.a));X.stroke()}
  else if(key==='moon'){X.strokeStyle='#b8fff0cc';X.shadowColor='#9fffe8';X.beginPath();X.arc(p.x,p.y,r+12,a,a+Math.PI*.85);X.stroke()}
  else if(key==='kill'){X.fillStyle='#fff0a6';X.shadowColor='#ffe065';star(X,p.x,p.y,5,5);X.fill()}
  else if(key==='combo'){X.strokeStyle='#ff9a5acc';X.shadowColor='#ff7c3d';X.beginPath();X.arc(p.x,p.y,r+5+8*((Math.sin(a)+1)/2),0,G.TAU);X.stroke()}
  else if(key==='core'){X.strokeStyle='#8ff6ff';X.shadowColor='#6eefff';poly(X,p.x,p.y,7+3*Math.sin(a),4,Math.PI/4);X.stroke()}
  else if(key==='split'){X.fillStyle='#8dff9d';X.shadowColor='#67ff8c';for(let k=0;k<3;k++){const aa=a+k*2.1;X.beginPath();X.ellipse(p.x+Math.cos(aa)*12,p.y+Math.sin(aa)*12,2,4,aa,0,G.TAU);X.fill()}}
  else if(key==='charge'){X.strokeStyle='#ffb15acc';X.shadowColor='#ff7b47';X.beginPath();X.arc(p.x,p.y,r+7,a,a+1.7);X.stroke();X.beginPath();X.arc(p.x,p.y,r+11,a+Math.PI,a+Math.PI+1.2);X.stroke()}
  else if(key==='tide'){X.strokeStyle='#63d8ffcc';X.shadowColor='#49caff';for(let k=0;k<2;k++){X.beginPath();X.arc(p.x,p.y,r+8+k*6,a+k,a+k+1.7);X.stroke()}}
  else if(key==='corpse'){X.strokeStyle='#ff5d7ecc';X.shadowColor='#c21f52';X.beginPath();X.moveTo(p.x-7,p.y+9);X.quadraticCurveTo(p.x+Math.sin(a)*12,p.y-12,p.x+8,p.y-8);X.stroke()}
  else if(key==='rudder'){X.strokeStyle='#a7c7ffcc';X.shadowColor='#78a8ff';X.beginPath();X.arc(p.x,p.y,r+12,a,a+2.4);X.stroke();X.beginPath();X.arc(p.x,p.y,r+6,a+Math.PI,a+Math.PI+1.7);X.stroke()}
  else if(key==='overload'){const cs=['#ff7aa8','#ffd76a','#7dffcb','#75c8ff','#c79cff'];for(let k=0;k<3;k++){X.fillStyle=cs[(i+k)%cs.length];X.shadowColor=X.fillStyle;const aa=a+k*2.1;X.beginPath();X.arc(p.x+Math.cos(aa)*(r+11),p.y+Math.sin(aa)*(r+11),2.3,0,G.TAU);X.fill()}}
 }X.shadowBlur=0;X.globalCompositeOperation='source-over';X.restore()}
function drawTail(s,skin,lv){if(!s.body.length)return;const X=G.ctx,z=G.camera.z,t=s.body[s.body.length-1],q=s.body[Math.max(0,s.body.length-6)]||t,p=G.screen(t.x,t.y),a=Math.atan2(t.y-q.y,t.x-q.x),r=s.radius*z*(.65+lv*.045);if(p.x<-120||p.x>G.vw+120||p.y<-120||p.y>G.vh+120)return;X.save();X.translate(p.x,p.y);X.rotate(a);X.fillStyle=skin.palette[0]+'dd';X.beginPath();if(lv<3){X.moveTo(0,0);X.quadraticCurveTo(-r*1.8,-r*.8,-r*2.2,0);X.quadraticCurveTo(-r*1.8,r*.8,0,0)}else if(lv<6){X.moveTo(0,0);X.lineTo(-r*2.1,-r*1.25);X.lineTo(-r*1.45,0);X.lineTo(-r*2.1,r*1.25);X.closePath()}else if(lv<8){for(const sy of [-1,1]){X.moveTo(0,0);X.quadraticCurveTo(-r*2.2,sy*r*1.8,-r*2.8,sy*r*.45);X.quadraticCurveTo(-r*1.5,sy*r*.35,0,0)}}else{for(let k=-1;k<=1;k++){const sy=k*.8;X.moveTo(0,0);X.quadraticCurveTo(-r*2.7,-r*(1.6-sy),-r*(3.1+Math.abs(k)*.2),r*sy);X.quadraticCurveTo(-r*1.7,r*sy*.45,0,0)}}X.fill();if(lv>=8){X.strokeStyle='#fff1a8';X.lineWidth=Math.max(1,1.5*z);X.beginPath();X.arc(-r*1.7,0,r*.9,0,G.TAU);X.stroke()}X.restore()}
function drawHead(s,skin,lv){const X=G.ctx,p=G.screen(s.x,s.y),z=G.camera.z,r=s.radius*z*1.1,size=r*(2.12+lv*.07),img=makeSegment(skin,lv,0);X.save();X.translate(p.x,p.y);X.rotate(s.a);X.drawImage(img,-size/2,-size/2,size,size);if(skin.motif!=='emoji'&&skin.motif!=='icon'){for(const sy of [-1,1]){X.fillStyle='#f8ffff';X.beginPath();X.arc(r*.38,sy*r*.42,r*.27,0,G.TAU);X.fill();X.fillStyle='#14203c';X.beginPath();X.arc(r*.48,sy*r*.42,r*(s.boosting?.15:.13),0,G.TAU);X.fill();X.fillStyle='#fff';X.beginPath();X.arc(r*.53,sy*r*.47,r*.05,0,G.TAU);X.fill()}X.strokeStyle='#25586e';X.lineWidth=Math.max(1,1.4*z);X.beginPath();X.arc(r*.75,0,r*.24,Math.PI*.7,Math.PI*1.3);X.stroke()}
 if(lv>=2){X.fillStyle='#edffffd8';for(const sy of [-1,1]){X.beginPath();X.moveTo(r*.08,sy*r*.48);X.lineTo(-r*.24,sy*r*(1.05+lv*.04));X.lineTo(r*.42,sy*r*.64);X.fill()}}
 if(lv>=4){X.fillStyle=skin.palette[0]+'e8';for(const sy of [-1,1]){X.beginPath();X.moveTo(r*.08,sy*r*.23);X.lineTo(r*.52,sy*r*(.8+lv*.04));X.lineTo(r*.66,sy*r*.35);X.fill()}}
 if(lv>=5){X.strokeStyle='#d9ffff99';X.lineWidth=Math.max(1,1.2*z);for(const sy of [-1,1]){X.beginPath();X.moveTo(r*.35,sy*r*.18);X.quadraticCurveTo(r*(1.3+lv*.04),sy*r*.5,r*1.75,sy*r*.08);X.stroke()}}
 if(lv>=6){X.fillStyle=skin.palette[0]+'aa';for(const sy of [-1,1]){X.beginPath();X.moveTo(-r*.15,sy*r*.62);X.quadraticCurveTo(-r*1.45,sy*r*(1.5+lv*.05),-r*.65,sy*r*.12);X.quadraticCurveTo(-r*1.0,sy*r*.72,-r*.15,sy*r*.62);X.fill()}}
 if(lv>=7){X.fillStyle='#efffffdc';for(let k=-1;k<=1;k++){const sy=k*.55;X.beginPath();X.moveTo(r*.05,sy*r*.45);X.lineTo(-r*.32,r*(sy-.9));X.lineTo(r*.38,sy*r*.55);X.fill()}}
 if(lv>=8){X.strokeStyle='#fff0a9';X.lineWidth=Math.max(1.2,2*z);X.beginPath();X.ellipse(-r*.08,0,r*1.38,r*.72,.08,0,G.TAU);X.stroke()}
 if(lv>=9){X.strokeStyle='#aef3ff';X.lineWidth=Math.max(1,1.5*z);X.beginPath();X.ellipse(-r*.08,0,r*1.58,r*.5,-.18,0,G.TAU);X.stroke();X.fillStyle='#fff7b8';for(let k=0;k<3;k++){const a=G.time*1.2+k*G.TAU/3;star(X,Math.cos(a)*r*1.45,Math.sin(a)*r*.66,Math.max(2,r*.12),5);X.fill()}}
 X.restore()}
function drawName(s,skin){const X=G.ctx,p=G.screen(s.x,s.y),z=G.camera.z;X.save();X.textAlign='center';X.font=`${Math.max(9,11*z)}px system-ui`;X.fillStyle=s===G.player?'#dffff6':'#dce6ffcc';X.shadowColor='#000';X.shadowBlur=3;X.fillText(`${skin.icon} ${s.name}${s.kills?'  ✦'+s.kills:''}`,p.x,p.y-s.radius*z-16);X.restore()}
G.Snake.prototype.draw=function(){if(this.dead)return;const X=G.ctx,z=G.camera.z||1,dx=this.x-G.camera.x,dy=this.y-G.camera.y,worldDist=Math.hypot(dx,dy),viewR=Math.hypot(G.vw,G.vh)/(2*z),tailReach=Math.min(4300,this.body.length*5.2+240);if(this!==G.player&&worldDist>viewR+tailReach)return;const head=G.screen(this.x,this.y),r=this.radius*z,crowd=G.renderCrowd||0,skin=skinOf(this),lv=Math.max(0,Math.min(9,G.stages.indexOf(this.stage))),near=worldDist<1500,mid=worldDist<3000;let stride=this===G.player?2:near?3:mid?5:8;if(crowd>22&&this!==G.player)stride=Math.max(stride,6);if(crowd>40&&this!==G.player)stride=Math.max(stride,9);X.save();for(let i=this.body.length-1;i>=0;i-=stride){const b=this.body[i],p=G.screen(b.x,b.y);if(p.x<-120||p.x>G.vw+120||p.y<-120||p.y>G.vh+120)continue;const rr=r*G.clamp(1-i/Math.max(1,this.body.length)*.46,.54,1),d=rr*(2.08+lv*.085),img=makeSegment(skin,lv,((i/Math.max(1,stride))|0)&1);X.drawImage(img,p.x-d/2,p.y-d/2,d,d)}drawTail(this,skin,lv);if(this===G.player&&this.buffs?.length)buffFx(this);if(head.x>-220&&head.x<G.vw+220&&head.y>-220&&head.y<G.vh+220){drawHead(this,skin,lv);if(crowd<45||this===G.player)drawName(this,skin)}X.restore()};
G.drawBackground=()=>{const X=G.ctx;X.fillStyle='#071027';X.fillRect(0,0,G.vw,G.vh);const sp=Math.max(48,80*(G.camera.z||1)),ox=(-G.camera.x*(G.camera.z||1)+G.vw/2)%sp,oy=(-G.camera.y*(G.camera.z||1)+G.vh/2)%sp;X.strokeStyle='#7babff0d';X.lineWidth=1;for(let x=ox;x<G.vw;x+=sp){X.beginPath();X.moveTo(x,0);X.lineTo(x,G.vh);X.stroke()}for(let y=oy;y<G.vh;y+=sp){X.beginPath();X.moveTo(0,y);X.lineTo(G.vw,y);X.stroke()}const gr=X.createRadialGradient(G.vw*.5,G.vh*.42,0,G.vw*.5,G.vh*.45,Math.max(G.vw,G.vh)*.72);gr.addColorStop(0,'#526fca20');gr.addColorStop(.5,'#28417e10');gr.addColorStop(1,'#01051488');X.fillStyle=gr;X.fillRect(0,0,G.vw,G.vh)};
})();