(()=>{
const G=window.EVO;
G.Snake.prototype.draw=function(){if(this.dead)return;const X=G.ctx,z=G.camera.z,r=this.radius*z;X.save();
 if(this.boosting&&this.trail){X.globalCompositeOperation='lighter';X.strokeStyle=this.palette[0]+'55';X.lineWidth=r*(1.35+this.trail*.15);X.lineCap='round';X.beginPath();for(let i=0;i<this.body.length;i+=3){const p=G.screen(this.body[i].x,this.body[i].y);i?X.lineTo(p.x,p.y):X.moveTo(p.x,p.y)}X.stroke();X.globalCompositeOperation='source-over'}
 X.shadowColor='#0008';X.shadowBlur=10*z;X.shadowOffsetY=4*z;
 for(let i=this.body.length-1;i>=0;i-=2){const b=this.body[i],p=G.screen(b.x,b.y),rr=r*G.clamp(1-i/this.body.length*.48,.52,1);const gr=X.createRadialGradient(p.x-rr*.35,p.y-rr*.4,1,p.x,p.y,rr);gr.addColorStop(0,'#fff');gr.addColorStop(.16,this.palette[0]);gr.addColorStop(.7,this.palette[1]);gr.addColorStop(1,this.palette[2]);X.fillStyle=gr;X.beginPath();X.arc(p.x,p.y,rr,0,G.TAU);X.fill();X.fillStyle='#ffffff32';X.beginPath();X.ellipse(p.x-rr*.28,p.y-rr*.3,rr*.2,rr*.1,-.5,0,G.TAU);X.fill();
  if(this.stage[1]>=150&&i%12===0){X.fillStyle=this.palette[0]+'b8';X.beginPath();X.moveTo(p.x,p.y-rr*.62);X.quadraticCurveTo(p.x-rr*1.05,p.y-rr*1.45,p.x+rr*.1,p.y-rr*.95);X.fill()}
  if(this.stage[1]>=760&&i%18===0&&i>8){X.strokeStyle='#ffffff32';X.lineWidth=Math.max(1,z);X.beginPath();X.arc(p.x,p.y,rr*.63,0,G.TAU);X.stroke()}
 }
 X.shadowBlur=0;drawHead(this);drawEvolution(this);drawAura(this);drawName(this);X.restore()};
function drawHead(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z*1.08;X.save();X.translate(p.x,p.y);X.rotate(s.a);const gr=X.createRadialGradient(-r*.35,-r*.42,1,0,0,r);gr.addColorStop(0,'#fff');gr.addColorStop(.2,s.palette[0]);gr.addColorStop(.72,s.palette[1]);gr.addColorStop(1,s.palette[2]);X.fillStyle=gr;X.beginPath();X.ellipse(0,0,r*1.1,r*.96,0,0,G.TAU);X.fill();
 for(const y of [-1,1]){X.fillStyle='#f8ffff';X.beginPath();X.arc(r*.35,y*r*.44,r*.28,0,G.TAU);X.fill();X.fillStyle='#14203c';X.beginPath();X.arc(r*.44,y*r*.44,r*(s.boosting?.15:.13),0,G.TAU);X.fill();X.fillStyle='#fff';X.beginPath();X.arc(r*.49,y*r*.49,r*.05,0,G.TAU);X.fill()}
 X.strokeStyle='#25586e';X.lineWidth=Math.max(1,1.5*G.camera.z);X.beginPath();X.arc(r*.71,0,r*.25,Math.PI*.7,Math.PI*1.3);X.stroke();X.restore()}
function drawEvolution(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z,lv=s.stage[1];X.save();X.translate(p.x,p.y);X.rotate(s.a);
 if(lv>=150){X.fillStyle=s.palette[0]+'d8';for(const y of [-1,1]){X.beginPath();X.moveTo(-r*.25,y*r*.7);X.quadraticCurveTo(-r*.95,y*r*1.28,-r*.72,y*r*.2);X.closePath();X.fill()}}
 if(lv>=380){X.fillStyle='#efffff';for(const y of [-1,1]){X.beginPath();X.moveTo(r*.12,y*r*.52);X.lineTo(-r*.28,y*r*1.5);X.lineTo(r*.5,y*r*.72);X.closePath();X.fill()}X.fillStyle='#b8fff0';X.beginPath();X.moveTo(r*.26,-r*.42);X.lineTo(r*.72,-r*.02);X.lineTo(r*.15,r*.04);X.fill()}
 if(lv>=760){X.fillStyle=s.palette[0]+'d5';for(const y of [-1,1]){X.beginPath();X.moveTo(-r*.18,y*r*.78);X.quadraticCurveTo(-r*1.55,y*r*2.0,-r*.72,y*r*.16);X.quadraticCurveTo(-r*1.0,y*r*.8,-r*.18,y*r*.78);X.fill()}X.strokeStyle='#d8ffff99';X.lineWidth=Math.max(1,1.4*G.camera.z);for(const y of [-1,1]){X.beginPath();X.moveTo(r*.4,y*r*.2);X.quadraticCurveTo(r*1.4,y*r*.48,r*1.75,y*r*.08);X.stroke()}}
 if(lv>=1350){X.shadowColor='#fff6a9';X.shadowBlur=14;X.strokeStyle='#fff1a8';X.lineWidth=Math.max(1.5,2.3*G.camera.z);X.beginPath();X.ellipse(-r*.2,0,r*1.55,r*.7,0,0,G.TAU);X.stroke();for(let k=0;k<4;k++){const a=G.time*1.45+k*G.TAU/4;X.fillStyle=k%2?'#fff8bd':'#b7f5ff';X.beginPath();X.arc(-r*.2+Math.cos(a)*r*1.55,Math.sin(a)*r*.7,Math.max(2,r*.12),0,G.TAU);X.fill()}X.shadowBlur=0}
 X.restore()}
function drawAura(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z;if(s.inv>0){X.strokeStyle='#ffffff66';X.lineWidth=2;X.setLineDash([4,5]);X.beginPath();X.arc(p.x,p.y,r+9,0,G.TAU);X.stroke();X.setLineDash([])}if(s.mag>28){X.strokeStyle='#64f4ff55';X.lineWidth=2;X.setLineDash([5,7]);X.beginPath();X.arc(p.x,p.y,r+25,0,G.TAU);X.stroke();X.setLineDash([])}for(let k=0;k<s.orbiters;k++){const a=G.time*1.8+k*G.TAU/s.orbiters,rr=r+28;X.fillStyle='#c69bff';X.shadowColor='#b476ff';X.shadowBlur=12;X.beginPath();X.arc(p.x+Math.cos(a)*rr,p.y+Math.sin(a)*rr,6,0,G.TAU);X.fill();X.shadowBlur=0}if(s.fins){X.strokeStyle='#8fffe866';for(let k=0;k<s.fins;k++){X.beginPath();X.arc(p.x,p.y,r+34+k*5,G.time+k,G.time+Math.PI*.9+k);X.stroke()}}}
function drawName(s){const X=G.ctx,p=G.screen(s.x,s.y),z=G.camera.z;X.save();X.textAlign='center';X.font=`${Math.max(9,11*z)}px system-ui`;X.fillStyle=s===G.player?'#dffff6':'#dce6ffcc';X.shadowColor='#000';X.shadowBlur=4;X.fillText(`${s.name}${s.kills?'  ✦'+s.kills:''}`,p.x,p.y-s.radius*z-14);X.restore()}
G.drawBackground=()=>{const X=G.ctx;X.fillStyle='#081027';X.fillRect(0,0,G.vw,G.vh);const sp=80*G.camera.z,ox=(-G.camera.x*G.camera.z+G.vw/2)%sp,oy=(-G.camera.y*G.camera.z+G.vh/2)%sp;X.strokeStyle='#7babff0d';for(let x=ox;x<G.vw;x+=sp){X.beginPath();X.moveTo(x,0);X.lineTo(x,G.vh);X.stroke()}for(let y=oy;y<G.vh;y+=sp){X.beginPath();X.moveTo(0,y);X.lineTo(G.vw,y);X.stroke()}const gr=X.createRadialGradient(G.vw*.5,G.vh*.42,0,G.vw*.5,G.vh*.45,Math.max(G.vw,G.vh)*.72);gr.addColorStop(0,'#526fca1c');gr.addColorStop(.48,'#2c4a9010');gr.addColorStop(1,'#01051482');X.fillStyle=gr;X.fillRect(0,0,G.vw,G.vh)};
})();