(()=>{
const G=window.EVO,segmentCache=new Map(),foodCache=new Map();
function makeSegment(pal){const key=pal.join('|');if(segmentCache.has(key))return segmentCache.get(key);const c=document.createElement('canvas');c.width=c.height=72;const x=c.getContext('2d'),g=x.createRadialGradient(27,24,2,36,36,32);g.addColorStop(0,'#fff');g.addColorStop(.16,pal[0]);g.addColorStop(.7,pal[1]);g.addColorStop(1,pal[2]);x.fillStyle=g;x.beginPath();x.arc(36,36,31,0,G.TAU);x.fill();x.fillStyle='#ffffff35';x.beginPath();x.ellipse(27,25,7,3,-.5,0,G.TAU);x.fill();segmentCache.set(key,c);return c}
function makeFood(color){if(foodCache.has(color))return foodCache.get(color);const c=document.createElement('canvas');c.width=c.height=40;const x=c.getContext('2d'),g=x.createRadialGradient(20,20,0,20,20,19);g.addColorStop(0,'#fff');g.addColorStop(.22,color);g.addColorStop(.58,color+'bb');g.addColorStop(1,'transparent');x.fillStyle=g;x.beginPath();x.arc(20,20,19,0,G.TAU);x.fill();foodCache.set(color,c);return c}
G.drawFoodSprite=f=>{const p=G.screen(f.x,f.y),r=f.r*G.camera.z;if(p.x<-22||p.x>G.vw+22||p.y<-22||p.y>G.vh+22)return;const s=Math.max(9,r*5.2),img=makeFood(f.c);G.ctx.drawImage(img,p.x-s/2,p.y-s/2,s,s)};
G.Snake.prototype.draw=function(){
 if(this.dead)return;const X=G.ctx,z=G.camera.z,worldDist=Math.hypot(this.x-G.camera.x,this.y-G.camera.y),viewR=Math.hypot(G.vw,G.vh)/(2*z),tailReach=Math.min(3600,this.body.length*5.2+180);if(worldDist>viewR+tailReach)return;
 const r=this.radius*z,head=G.screen(this.x,this.y),near=worldDist<1350,mid=worldDist<2700,crowd=G.renderCrowd||0;
 let stride=this===G.player?2:near?3:mid?5:7;if(crowd>18&&this!==G.player)stride=Math.max(stride,5);if(crowd>35&&this!==G.player)stride=Math.max(stride,8);
 const rich=(this===G.player||crowd<18)&&near,img=makeSegment(this.palette);X.save();
 if(this.boosting&&this.trail&&worldDist<viewR+420&&crowd<28){X.globalCompositeOperation='lighter';X.strokeStyle=this.palette[0]+'55';X.lineWidth=r*(1.35+this.trail*.15);X.lineCap='round';X.beginPath();let started=false;for(let i=0;i<this.body.length;i+=Math.max(4,stride)){const p=G.screen(this.body[i].x,this.body[i].y);if(p.x<-120||p.x>G.vw+120||p.y<-120||p.y>G.vh+120)continue;started?X.lineTo(p.x,p.y):(X.moveTo(p.x,p.y),started=true)}if(started)X.stroke();X.globalCompositeOperation='source-over'}
 if(rich){X.shadowColor='#0007';X.shadowBlur=7*z;X.shadowOffsetY=3*z}
 for(let i=this.body.length-1;i>=0;i-=stride){const b=this.body[i],p=G.screen(b.x,b.y);if(p.x<-80||p.x>G.vw+80||p.y<-80||p.y>G.vh+80)continue;const rr=r*G.clamp(1-i/this.body.length*.48,.52,1),d=rr*2.15;X.drawImage(img,p.x-d/2,p.y-d/2,d,d);
  if(rich&&this.stage[1]>=150&&i%12===0){X.fillStyle=this.palette[0]+'b8';X.beginPath();X.moveTo(p.x,p.y-rr*.62);X.quadraticCurveTo(p.x-rr*1.05,p.y-rr*1.45,p.x+rr*.1,p.y-rr*.95);X.fill()}
  if(rich&&this.stage[1]>=760&&i%18===0&&i>8){X.strokeStyle='#ffffff32';X.lineWidth=Math.max(1,z);X.beginPath();X.arc(p.x,p.y,rr*.63,0,G.TAU);X.stroke()}
 }
 X.shadowBlur=0;if(head.x>-180&&head.x<G.vw+180&&head.y>-180&&head.y<G.vh+180){drawHead(this);drawEvolution(this);if(rich)drawAura(this);if(crowd<42||this===G.player)drawName(this)}X.restore()
};
function drawHead(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z*1.08;X.save();X.translate(p.x,p.y);X.rotate(s.a);const img=makeSegment(s.palette);X.drawImage(img,-r*1.13,-r*1.02,r*2.26,r*2.04);for(const y of [-1,1]){X.fillStyle='#f8ffff';X.beginPath();X.arc(r*.35,y*r*.44,r*.28,0,G.TAU);X.fill();X.fillStyle='#14203c';X.beginPath();X.arc(r*.44,y*r*.44,r*(s.boosting?.15:.13),0,G.TAU);X.fill();X.fillStyle='#fff';X.beginPath();X.arc(r*.49,y*r*.49,r*.05,0,G.TAU);X.fill()}X.strokeStyle='#25586e';X.lineWidth=Math.max(1,1.5*G.camera.z);X.beginPath();X.arc(r*.71,0,r*.25,Math.PI*.7,Math.PI*1.3);X.stroke();X.restore()}
function drawEvolution(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z,lv=s.stage[1];X.save();X.translate(p.x,p.y);X.rotate(s.a);if(lv>=150){X.fillStyle=s.palette[0]+'d8';for(const y of [-1,1]){X.beginPath();X.moveTo(-r*.25,y*r*.7);X.quadraticCurveTo(-r*.95,y*r*1.28,-r*.72,y*r*.2);X.closePath();X.fill()}}if(lv>=380){X.fillStyle='#efffff';for(const y of [-1,1]){X.beginPath();X.moveTo(r*.12,y*r*.52);X.lineTo(-r*.28,y*r*1.5);X.lineTo(r*.5,y*r*.72);X.closePath();X.fill()}X.fillStyle='#b8fff0';X.beginPath();X.moveTo(r*.26,-r*.42);X.lineTo(r*.72,-r*.02);X.lineTo(r*.15,r*.04);X.fill()}if(lv>=760){X.fillStyle=s.palette[0]+'d5';for(const y of [-1,1]){X.beginPath();X.moveTo(-r*.18,y*r*.78);X.quadraticCurveTo(-r*1.55,y*r*2,-r*.72,y*r*.16);X.quadraticCurveTo(-r,y*r*.8,-r*.18,y*r*.78);X.fill()}X.strokeStyle='#d8ffff99';X.lineWidth=Math.max(1,1.4*G.camera.z);for(const y of [-1,1]){X.beginPath();X.moveTo(r*.4,y*r*.2);X.quadraticCurveTo(r*1.4,y*r*.48,r*1.75,y*r*.08);X.stroke()}}if(lv>=1350&&G.renderCrowd<30){X.strokeStyle='#fff1a8';X.lineWidth=Math.max(1.5,2.3*G.camera.z);X.beginPath();X.ellipse(-r*.2,0,r*1.55,r*.7,0,0,G.TAU);X.stroke();for(let k=0;k<4;k++){const a=G.time*1.45+k*G.TAU/4;X.fillStyle=k%2?'#fff8bd':'#b7f5ff';X.beginPath();X.arc(-r*.2+Math.cos(a)*r*1.55,Math.sin(a)*r*.7,Math.max(2,r*.12),0,G.TAU);X.fill()}}X.restore()}
function drawAura(s){const X=G.ctx,p=G.screen(s.x,s.y),r=s.radius*G.camera.z;if(s.inv>0){X.strokeStyle='#ffffff66';X.lineWidth=2;X.setLineDash([4,5]);X.beginPath();X.arc(p.x,p.y,r+9,0,G.TAU);X.stroke();X.setLineDash([])}if(s.mag>28){X.strokeStyle='#64f4ff55';X.lineWidth=2;X.setLineDash([5,7]);X.beginPath();X.arc(p.x,p.y,r+25,0,G.TAU);X.stroke();X.setLineDash([])}for(let k=0;k<s.orbiters;k++){const a=G.time*1.8+k*G.TAU/s.orbiters,rr=r+28;X.fillStyle='#c69bff';X.beginPath();X.arc(p.x+Math.cos(a)*rr,p.y+Math.sin(a)*rr,6,0,G.TAU);X.fill()}if(s.fins){X.strokeStyle='#8fffe866';for(let k=0;k<s.fins;k++){X.beginPath();X.arc(p.x,p.y,r+34+k*5,G.time+k,G.time+Math.PI*.9+k);X.stroke()}}}
function drawName(s){const X=G.ctx,p=G.screen(s.x,s.y),z=G.camera.z;X.save();X.textAlign='center';X.font=`${Math.max(9,11*z)}px system-ui`;X.fillStyle=s===G.player?'#dffff6':'#dce6ffcc';X.fillText(`${s.name}${s.kills?'  ✦'+s.kills:''}`,p.x,p.y-s.radius*z-14);X.restore()}
G.drawBackground=()=>{const X=G.ctx;X.fillStyle='#081027';X.fillRect(0,0,G.vw,G.vh);const sp=80*G.camera.z,ox=(-G.camera.x*G.camera.z+G.vw/2)%sp,oy=(-G.camera.y*G.camera.z+G.vh/2)%sp;X.strokeStyle='#7babff0d';for(let x=ox;x<G.vw;x+=sp){X.beginPath();X.moveTo(x,0);X.lineTo(x,G.vh);X.stroke()}for(let y=oy;y<G.vh;y+=sp){X.beginPath();X.moveTo(0,y);X.lineTo(G.vw,y);X.stroke()}const gr=X.createRadialGradient(G.vw*.5,G.vh*.42,0,G.vw*.5,G.vh*.45,Math.max(G.vw,G.vh)*.72);gr.addColorStop(0,'#526fca1c');gr.addColorStop(.48,'#2c4a9010');gr.addColorStop(1,'#01051482');X.fillStyle=gr;X.fillRect(0,0,G.vw,G.vh)};
})();