const assert=require('node:assert');
const path=require('node:path');
const fs=require('node:fs');
const C=require('../minigame/src/config');
const {Game,Snake,Food}=require('../minigame/src/engine');
const {Renderer}=require('../minigame/src/render');
const {Input}=require('../minigame/src/input');
const A=require('../minigame/src/advanced');
A.installAdvanced({Game,Snake,Food,Renderer,Input});
assert.equal(C.STAGES.length,10,'mini game must keep 10 evolution stages');
assert.equal(C.BUFFS.length,16,'mini game must keep 16 buffs');
assert.equal(C.SKINS.length,30,'mini game must keep 30 skins');
assert.equal(A.BRANCHES.length,3,'advanced progression needs three evolution branches');
assert(A.SYNERGIES.length>=6,'advanced progression needs buff synergies');
assert(A.MUTATIONS.length>=9,'advanced progression needs rare mutations');
assert(A.HOTSPOTS.length>=4,'advanced progression needs map hotspots');
const gameJson=JSON.parse(fs.readFileSync(path.join(__dirname,'../minigame/game.json'),'utf8'));
assert.equal(gameJson.deviceOrientation,'landscape','WeChat Mini Game must lock landscape');
const g=new Game({width:844,height:390});g.start(0);assert.equal(g.state,'playing');assert.equal(g.snakes.length,31);assert(g.foods.length>=2250,'hotspots should seed extra stars');g.player.inv=999;const x0=g.player.x,y0=g.player.y;g.player.ta=0;for(let i=0;i<45;i++)g.update(1/60);assert(Math.hypot(g.player.x-x0,g.player.y-y0)>50,'player movement should advance');
g.player.score=111;g.update(1/60);assert.equal(g.state,'upgrade','upgrade should pause gameplay at threshold');assert.equal(g.choices.length,3);assert(g.chooseBuff(0));assert.equal(g.state,'playing');assert.equal(g.player.buffs.length,1);
g.nextUpgrade=999;g.player.score=650;g.update(1/60);assert.equal(g.state,'branch','score 600 should trigger route choice');assert.equal(g.branchChoices.length,3);assert(g.chooseBranch(0));assert.equal(g.branch.id,'tide');assert.equal(g.state,'playing');
g.player.buffs=[C.BUFFS.find(b=>b.id==='magnet'),C.BUFFS.find(b=>b.id==='tide')];const gained=g.resolveSynergies();assert(gained.some(s=>s.id==='gravity-tide'),'matching buffs should unlock synergy');
g.player.score=1900;g.update(1/60);assert.equal(g.state,'mutation','mid game should trigger rare mutation');assert.equal(g.mutationChoices.length,3);assert(g.chooseMutation(0));assert.equal(g.mutations.length,1);assert.equal(g.state,'playing');
g.foods=[];g.spatial.rebuild(g);g.ensureLocalFood();assert(g.foods.length>0,'local star floor should repopulate empty area');g.maintainHotspots();assert(g.foods.length>20,'hotspots should repopulate contested resources');
const fair=new Game({width:844,height:390});fair.start(0);const small=fair.snakes.find(s=>s.ai);fair.player.score=5000;small.score=60;fair.player.x=small.x=5000;fair.player.y=small.y=4000;fair.player.inv=small.inv=0;fair.spatial.rebuild(fair);fair.player.checkCollision();assert(fair.player.dead&&small.dead,'head-to-head must kill both regardless of size');
let touchStart,touchMove,touchEnd,touchCancel;const gradient={addColorStop(){}};const ctx=new Proxy({measureText:t=>({width:String(t).length*7}),createRadialGradient:()=>gradient,setTransform(){},fillRect(){},beginPath(){},rect(){},fill(){},stroke(){},arc(){},ellipse(){},moveTo(){},lineTo(){},closePath(){},save(){},restore(){},translate(){},rotate(){},quadraticCurveTo(){},fillText(){},setLineDash(){}},{get(o,k){if(k in o)return o[k];return ()=>{}},set(o,k,v){o[k]=v;return true}});const canvas={width:0,height:0,getContext:()=>ctx,requestAnimationFrame:()=>1,cancelAnimationFrame(){}};
global.wx={createCanvas:()=>canvas,getWindowInfo:()=>({windowWidth:844,windowHeight:390,pixelRatio:2}),onWindowResize(){},onTouchStart:fn=>touchStart=fn,onTouchMove:fn=>touchMove=fn,onTouchEnd:fn=>touchEnd=fn,onTouchCancel:fn=>touchCancel=fn,getStorageSync:()=>0,setStorageSync(){},setKeepScreenOn(){},vibrateShort(){}};
const {boot}=require('../minigame/src/main');const runtime=boot();assert.equal(runtime.platform.width,844);assert.equal(runtime.platform.height,390);const start=runtime.renderer.hitboxes.start;touchStart({changedTouches:[{identifier:1,clientX:start.x+start.w/2,clientY:start.y+start.h/2}]});assert.equal(runtime.game.state,'playing','intro start button should launch game');runtime.renderer.draw();touchStart({changedTouches:[{identifier:11,clientX:runtime.input.joy.cx,clientY:runtime.input.joy.cy-runtime.input.joy.r*.7}]});runtime.input.apply();assert.equal(runtime.input.joy.id,11,'left touch should own joystick');touchStart({changedTouches:[{identifier:12,clientX:runtime.input.boostRect.cx,clientY:runtime.input.boostRect.cy}]});assert(runtime.game.player.boosting,'right touch should enable boost');touchEnd({changedTouches:[{identifier:12,clientX:0,clientY:0}]});assert(!runtime.game.player.boosting,'boost should stop on touch end');
runtime.game.nextUpgrade=999;runtime.game.player.score=650;runtime.game.update(1/60);runtime.renderer.draw();assert.equal(runtime.game.state,'branch');assert.equal(runtime.renderer.hitboxes.branch.length,3,'branch overlay needs three touch cards');const bc=runtime.renderer.hitboxes.branch[1];touchStart({changedTouches:[{identifier:20,clientX:bc.x+bc.w/2,clientY:bc.y+bc.h/2}]});assert.equal(runtime.game.state,'playing','touch should choose branch');runtime.stop();
console.log('MINIGAME PASS: landscape, controls, fair collision, 10 stages, 16 buffs, 30 skins, 3 branches, synergies, rare mutations and 4 hotspots passed.');
