const {WORLD,STAGES,SKINS,TAU,clamp}=require('./config');
class Renderer{
  constructor(platform,game){this.p=platform;this.g=game;this.ctx=platform.ctx;this.camera={x:WORLD.w/2,y:WORLD.h/2,z:.7};this.hitboxes={};this.input=null}
  setInput(input){this.input=input}
  resize(){this.g.setViewport(this.p.width,this.p.height)}
  screen(x,y){return{x:(x-this.camera.x)*this.camera.z+this.p.width/2,y:(y-this.camera.y)*this.camera.z+this.p.height/2}}
  updateCamera(){const P=this.g.player;if(!P||P.dead)return;const targetZ=clamp((this.p.height/900)*(1-Math.min(.18,Math.sqrt(P.score)/3000)),.38,.88);this.camera.x+= (P.x-this.camera.x)*.16;this.camera.y+=(P.y-this.camera.y)*.16;this.camera.z+=(targetZ-this.camera.z)*.12;if(!Number.isFinite(this.camera.x)||Math.hypot(this.camera.x-P.x,this.camera.y-P.y)>2200){this.camera.x=P.x;this.camera.y=P.y}}
  begin(){const X=this.ctx;X.setTransform&&X.setTransform(this.p.ratio,0,0,this.p.ratio,0,0);X.globalAlpha=1;X.globalCompositeOperation='source-over';X.fillStyle='#071027';X.fillRect(0,0,this.p.width,this.p.height)}
  background(){const X=this.ctx,w=this.p.width,h=this.p.height,z=this.camera.z;X.fillStyle='#08122b';X.fillRect(0,0,w,h);const step=300*z,ox=((WORLD.w/2-this.camera.x)*z+w/2)%step,oy=((WORLD.h/2-this.camera.y)*z+h/2)%step;X.strokeStyle='rgba(88,136,210,.08)';X.lineWidth=1;X.beginPath();for(let x=ox-step;x<w+step;x+=step){X.moveTo(x,0);X.lineTo(x,h)}for(let y=oy-step;y<h+step;y+=step){X.moveTo(0,y);X.lineTo(w,y)}X.stroke();const grd=X.createRadialGradient(w*.5,h*.45,10,w*.5,h*.45,Math.max(w,h)*.65);grd.addColorStop(0,'rgba(36,70,140,.12)');grd.addColorStop(1,'rgba(4,8,20,.0)');X.fillStyle=grd;X.fillRect(0,0,w,h)}
  drawFood(){const X=this.ctx,z=this.camera.z,viewR=Math.hypot(this.p.width,this.p.height)/(2*z)+160,foods=this.g.spatial.foodsNear(this.camera.x,this.camera.y,viewR);for(const f of foods){if(f.dead)continue;const q=this.screen(f.x,f.y);if(q.x<-12||q.x>this.p.width+12||q.y<-12||q.y>this.p.height+12)continue;const r=Math.max(2.2,f.r*z);X.globalAlpha=.26;X.fillStyle=f.c;X.beginPath();X.arc(q.x,q.y,r*2.2,0,TAU);X.fill();X.globalAlpha=1;X.fillStyle=f.c;X.beginPath();X.arc(q.x,q.y,r,0,TAU);X.fill();X.fillStyle='rgba(255,255,255,.78)';X.beginPath();X.arc(q.x-r*.28,q.y-r*.28,Math.max(.8,r*.22),0,TAU);X.fill()}X.globalAlpha=1}
  polygon(cx,cy,r,n,rot,fill,stroke){const X=this.ctx;X.beginPath();for(let i=0;i<n;i++){const a=rot+i*TAU/n,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?X.lineTo(x,y):X.moveTo(x,y)}X.closePath();if(fill){X.fillStyle=fill;X.fill()}if(stroke){X.strokeStyle=stroke;X.stroke()}}
  segment(s,q,r,stage,idx){const X=this.ctx,skin=s.skin,p=skin.palette,shape=skin.shape,m=skin.motif;if(shape==='crystal')this.polygon(q.x,q.y,r,6,Math.PI/6,p[1]);else if(shape==='mech')this.polygon(q.x,q.y,r,8,Math.PI/8,p[1]);else if(shape==='cloud'){X.fillStyle=p[1];for(const [dx,dy,k] of [[-.35,.12,.7],[.1,-.18,.82],[.42,.12,.62]]){X.beginPath();X.arc(q.x+dx*r,q.y+dy*r,r*k,0,TAU);X.fill()}}else{X.fillStyle=p[1];X.beginPath();X.ellipse(q.x,q.y,r*(shape==='scale'?1.08:1),r*(shape==='scale'?.86:1),0,0,TAU);X.fill()}
    X.fillStyle='rgba(255,255,255,.26)';X.beginPath();X.arc(q.x-r*.28,q.y-r*.3,Math.max(1,r*.18),0,TAU);X.fill();
    if((m==='emoji'||m==='icon')&&idx%3===0&&r>7){X.font=`${Math.max(11,r*1.4)}px sans-serif`;X.textAlign='center';X.textBaseline='middle';X.fillText(skin.icon,q.x,q.y+1)}else if(m==='bone'&&idx%2===0){X.strokeStyle='#6c7185';X.lineWidth=Math.max(1,r*.18);X.beginPath();X.moveTo(q.x-r*.55,q.y);X.lineTo(q.x+r*.55,q.y);X.stroke()}else if(m==='circuit'&&idx%3===0){X.strokeStyle='#7fffff';X.lineWidth=1;X.beginPath();X.moveTo(q.x-r*.5,q.y-r*.15);X.lineTo(q.x,q.y-r*.15);X.lineTo(q.x,q.y+r*.35);X.lineTo(q.x+r*.5,q.y+r*.35);X.stroke()}else if((m==='strawberry'||m==='watermelon'||m==='spots')&&idx%2===0){X.fillStyle=m==='watermelon'?'#342342':'rgba(255,255,220,.75)';for(let k=0;k<3;k++){const a=k*2.1+idx;X.beginPath();X.arc(q.x+Math.cos(a)*r*.45,q.y+Math.sin(a)*r*.45,Math.max(1,r*.09),0,TAU);X.fill()}}
    if(stage>=2&&idx%2===0){X.fillStyle=p[0];X.beginPath();X.moveTo(q.x,q.y-r*.65);X.lineTo(q.x-r*.24,q.y-r*(1.08+.03*stage));X.lineTo(q.x+r*.24,q.y-r*.65);X.closePath();X.fill()}
    if(stage>=4&&idx%3===0){X.strokeStyle=p[0]+'cc';X.lineWidth=Math.max(1,r*.13);X.beginPath();X.moveTo(q.x-r*.62,q.y);X.lineTo(q.x-r*(1.1+.04*stage),q.y-r*.42);X.moveTo(q.x+r*.62,q.y);X.lineTo(q.x+r*(1.1+.04*stage),q.y+r*.42);X.stroke()}
    if(stage>=6&&idx%4===0){X.strokeStyle='rgba(170,235,255,.34)';X.lineWidth=Math.max(1,r*.08);X.beginPath();X.arc(q.x,q.y,r*(1.25+.04*stage),0,TAU);X.stroke()}
    if(stage>=8&&idx%7===0){X.strokeStyle='rgba(255,240,160,.58)';X.lineWidth=1;X.beginPath();X.ellipse(q.x,q.y,r*1.65,r*.72,.35,0,TAU);X.stroke()}
  }
  drawTail(s,stage){if(s.body.length<4)return;const t=s.body[s.body.length-1],b=s.body[Math.max(0,s.body.length-5)],q=this.screen(t.x,t.y),a=Math.atan2(t.y-b.y,t.x-b.x),r=s.radius*this.camera.z;const X=this.ctx;X.save();X.translate(q.x,q.y);X.rotate(a);X.fillStyle=s.palette[0];X.beginPath();if(stage<3){X.moveTo(0,0);X.quadraticCurveTo(-r*2,-r*.7,-r*2.4,0);X.quadraticCurveTo(-r*2,r*.7,0,0)}else{X.moveTo(0,0);X.lineTo(-r*2.4,-r*(.9+stage*.07));X.lineTo(-r*1.6,0);X.lineTo(-r*2.4,r*(.9+stage*.07));X.closePath()}X.fill();X.restore()}
  drawHead(s,stage){const X=this.ctx,q=this.screen(s.x,s.y),r=s.radius*this.camera.z*(1.15+stage*.018);X.save();X.translate(q.x,q.y);X.rotate(s.a);X.fillStyle=s.palette[1];X.beginPath();X.ellipse(0,0,r*1.16,r*.94,0,0,TAU);X.fill();if(s.skin.motif!=='emoji'&&s.skin.motif!=='icon'){for(const yy of [-1,1]){X.fillStyle='#f7ffff';X.beginPath();X.arc(r*.42,yy*r*.42,r*.25,0,TAU);X.fill();X.fillStyle='#17213c';X.beginPath();X.arc(r*.5,yy*r*.42,r*.12,0,TAU);X.fill()}}else{X.font=`${Math.max(15,r*1.45)}px sans-serif`;X.textAlign='center';X.textBaseline='middle';X.fillText(s.skin.icon,0,0)}if(stage>=3){X.fillStyle=s.palette[0];for(const yy of [-1,1]){X.beginPath();X.moveTo(r*.05,yy*r*.5);X.lineTo(-r*.45,yy*r*(1.15+stage*.05));X.lineTo(r*.42,yy*r*.68);X.closePath();X.fill()}}if(stage>=7){X.strokeStyle='rgba(255,245,180,.7)';X.lineWidth=2;X.beginPath();X.arc(0,0,r*1.5,0,TAU);X.stroke()}X.restore()}
  bodyPoint(s,phase,speed=1){if(!s.body.length)return null;const n=s.body.length,i=Math.min(n-1,Math.max(0,Math.floor(((this.g.time*speed+phase)%1)*n)));return this.screen(s.body[i].x,s.body[i].y)}
  buffFx(s){const X=this.ctx,z=this.camera.z;for(let i=0;i<s.buffs.length;i++){const b=s.buffs[i],p=this.bodyPoint(s,(i*.173)%1,.08+(i%4)*.015);if(!p)continue;const r=Math.max(5,s.radius*z*.72),t=this.g.time+i;X.save();switch(b.fx){case'magnet':X.strokeStyle='#6fffee';X.lineWidth=2;X.beginPath();X.arc(p.x,p.y,r*(1.4+.25*Math.sin(t*3)),0,TAU);X.stroke();break;case'speed':X.strokeStyle='#ffe36a';X.lineWidth=2;X.beginPath();X.moveTo(p.x-r,p.y+r*.4);X.lineTo(p.x,p.y-r*.8);X.lineTo(p.x+r*.15,p.y);X.lineTo(p.x+r,p.y-r*.45);X.stroke();break;case'feast':for(let k=0;k<3;k++){X.fillStyle='#ff85c7';X.beginPath();X.arc(p.x+(k-1)*r*.55,p.y+Math.sin(t*4+k)*r*.35,Math.max(2,r*.18),0,TAU);X.fill()}break;case'turn':X.strokeStyle='rgba(245,255,255,.86)';X.lineWidth=2;X.beginPath();X.arc(p.x,p.y,r*1.25,-1.1,.8);X.stroke();X.beginPath();X.arc(p.x,p.y,r*.9,2,4);X.stroke();break;case'spore':for(let k=0;k<4;k++){const a=t*1.8+k*TAU/4;X.fillStyle='#c090ff';X.beginPath();X.arc(p.x+Math.cos(a)*r*1.15,p.y+Math.sin(a)*r*1.15,Math.max(2,r*.16),0,TAU);X.fill()}break;case'comet':X.strokeStyle='#6bbcff';X.lineWidth=Math.max(2,r*.25);X.beginPath();X.moveTo(p.x-r*1.4,p.y+r*.5);X.lineTo(p.x+r*.9,p.y-r*.5);X.stroke();break;case'moon':X.strokeStyle='#b9d7ff';X.lineWidth=2;X.beginPath();X.arc(p.x,p.y,r*1.2,-1.4,1.1);X.stroke();break;case'kill':for(let k=0;k<3;k++){const a=t+k*2.1;X.fillStyle='#ffe890';X.fillRect(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,2.5,2.5)}break;case'combo':X.strokeStyle='#ff9860';X.lineWidth=3;X.globalAlpha=.5+.5*Math.sin(t*7);X.beginPath();X.arc(p.x,p.y,r*1.35,0,TAU);X.stroke();break;case'core':this.polygon(p.x,p.y,r*.75,4,Math.PI/4,'rgba(100,245,255,.55)','#d7ffff');break;case'split':for(let k=0;k<3;k++){X.fillStyle='#8fff9b';X.beginPath();X.ellipse(p.x+(k-1)*r*.7,p.y+Math.cos(t*2+k)*r*.45,r*.18,r*.3,k,0,TAU);X.fill()}break;case'charge':X.strokeStyle='#ff6d4d';X.lineWidth=3;X.beginPath();X.arc(p.x,p.y,r*(1+.35*(s.charge||0)),0,TAU);X.stroke();break;case'tide':X.strokeStyle='#62caff';X.lineWidth=2;X.beginPath();X.moveTo(p.x-r*1.3,p.y);X.quadraticCurveTo(p.x-r*.5,p.y-r,p.x,p.y);X.quadraticCurveTo(p.x+r*.5,p.y+r,p.x+r*1.3,p.y);X.stroke();break;case'corpse':X.strokeStyle='#d6a5ff';X.lineWidth=2;for(let k=0;k<3;k++){X.beginPath();X.moveTo(p.x-r*.8+k*r*.7,p.y-r*.5);X.lineTo(p.x-r*.3+k*r*.7,p.y+r*.5);X.stroke()}break;case'rudder':X.strokeStyle='#6ffff2';X.lineWidth=2;X.beginPath();X.arc(p.x,p.y,r*1.1,t,t+Math.PI*1.5);X.stroke();break;case'overload':for(let k=0;k<4;k++){X.strokeStyle=['#ff657a','#ffd85a','#73f1c5','#83a8ff'][k];X.lineWidth=2;X.beginPath();X.arc(p.x,p.y,r*(.7+k*.18),t+k,t+k+1.3);X.stroke()}break}X.restore()}}
  drawSnake(s,player=false,crowd=0){if(s.dead)return;const z=this.camera.z,stage=s.stageIndex,dist=Math.hypot(s.x-this.camera.x,s.y-this.camera.y),view=Math.hypot(this.p.width,this.p.height)/(2*z);if(!player&&dist>view+1800)return;let stride=player?2:dist<1500?3:5;if(crowd>24&&!player)stride=Math.max(stride,6);for(let i=s.body.length-1;i>=0;i-=stride){const b=s.body[i],q=this.screen(b.x,b.y);if(q.x<-80||q.x>this.p.width+80||q.y<-80||q.y>this.p.height+80)continue;const taper=clamp(1-i/s.body.length*.45,.55,1),r=Math.max(3,s.radius*z*taper*(1+stage*.016));this.segment(s,q,r,stage,i)}this.drawTail(s,stage);if(player&&s.buffs.length)this.buffFx(s);this.drawHead(s,stage);const h=this.screen(s.x,s.y);if(player||crowd<24){const X=this.ctx;X.font='11px sans-serif';X.textAlign='center';X.fillStyle=player?'#cffff0':'rgba(220,235,255,.72)';X.fillText(`${s.name}${s.kills?' ✦'+s.kills:''}`,h.x,h.y-s.radius*z*2.2)}}
  drawParticles(){const X=this.ctx;for(const p of this.g.particles){const q=this.screen(p.x,p.y);if(q.x<-10||q.x>this.p.width+10||q.y<-10||q.y>this.p.height+10)continue;X.globalAlpha=clamp(p.life*2,0,1);X.fillStyle=p.c;X.beginPath();X.arc(q.x,q.y,Math.max(1,p.r*this.camera.z),0,TAU);X.fill()}X.globalAlpha=1}
  world(){this.updateCamera();this.background();this.drawFood();const P=this.g.player;let crowd=0;if(P)for(const s of this.g.snakes)if(!s.dead&&Math.hypot(s.x-P.x,s.y-P.y)<2200)crowd++;const bots=this.g.snakes.filter(s=>s!==P&&!s.dead).sort((a,b)=>a.score-b.score);for(const s of bots)this.drawSnake(s,false,crowd);if(P&&!P.dead)this.drawSnake(P,true,crowd);this.drawParticles()}
  panel(x,y,w,h,alpha=.72){const X=this.ctx;X.fillStyle=`rgba(12,21,48,${alpha})`;X.strokeStyle='rgba(190,220,255,.18)';X.lineWidth=1;X.beginPath();X.rect(x,y,w,h);X.fill();X.stroke()}
  hud(){const P=this.g.player;if(!P)return;const X=this.ctx,w=this.p.width;this.panel(16,14,178,108,.62);X.textAlign='left';X.fillStyle='#eaffff';X.font='bold 14px sans-serif';X.fillText('● 萌鳞进化',30,36);X.font='12px sans-serif';X.fillStyle='#9eb1d6';X.fillText('长度',30,59);X.fillText('阶段',30,79);X.fillText('反杀',30,99);X.textAlign='right';X.fillStyle='#fff';X.font='bold 13px sans-serif';X.fillText(Math.floor(P.score),178,59);X.fillText(P.stage[0],178,79);X.fillText(P.kills,178,99);this.panel(w-176,14,160,108,.62);const rank=this.g.snakes.filter(s=>!s.dead).sort((a,b)=>b.score-a.score).slice(0,5);X.textAlign='left';X.fillStyle='#8196c0';X.font='11px sans-serif';X.fillText('本局排行',w-158,35);X.fillStyle='#dce8ff';for(let i=0;i<rank.length;i++)X.fillText(`${i+1}. ${rank[i].name} · ${Math.floor(rank[i].score)}`,w-158,54+i*14)}
  controls(){if(!this.input||this.g.state!=='playing')return;const X=this.ctx,j=this.input.joy,b=this.input.boostRect;X.globalAlpha=.5;X.strokeStyle='rgba(210,235,255,.45)';X.lineWidth=2;X.beginPath();X.arc(j.cx,j.cy,j.r,0,TAU);X.stroke();X.fillStyle='rgba(100,215,255,.45)';X.beginPath();X.arc(j.cx+j.dx,j.cy+j.dy,j.r*.42,0,TAU);X.fill();X.strokeStyle='rgba(255,220,150,.55)';X.fillStyle='rgba(80,42,60,.34)';X.beginPath();X.arc(b.cx,b.cy,b.r,0,TAU);X.fill();X.stroke();X.globalAlpha=1;X.textAlign='center';X.fillStyle='#ffe6b0';X.font='bold 22px sans-serif';X.fillText('⚡',b.cx,b.cy-2);X.font='10px sans-serif';X.fillText('按住冲刺',b.cx,b.cy+20)}
  intro(){const X=this.ctx,w=this.p.width,h=this.p.height,skin=SKINS[this.g.skinIndex];X.fillStyle='#071027';X.fillRect(0,0,w,h);const pw=Math.min(620,w-40),ph=Math.min(360,h-32),x=(w-pw)/2,y=(h-ph)/2;this.panel(x,y,pw,ph,.92);X.textAlign='center';X.fillStyle='#7deeff';X.font='10px sans-serif';X.fillText('WECHAT MINI GAME · LANDSCAPE',w/2,y+28);X.fillStyle='#fff';X.font='bold 34px sans-serif';X.fillText('萌鳞进化 · EvoSnake',w/2,y+72);X.fillStyle='#9eb0d2';X.font='12px sans-serif';X.fillText('真横屏 · 全屏 Canvas · 10 阶进化 · 16 Buff · 30 皮肤',w/2,y+100);X.font='42px sans-serif';X.fillText(skin.icon,w/2,y+153);X.font='bold 15px sans-serif';X.fillStyle='#eafaff';X.fillText(`${this.g.skinIndex+1}/30  ${skin.name}`,w/2,y+182);const cy=y+180;this.hitboxes.prev={x:w/2-145,y:cy-28,w:46,h:56};this.hitboxes.next={x:w/2+99,y:cy-28,w:46,h:56};this.hitboxes.random={x:w/2+155,y:cy-28,w:54,h:56};X.font='bold 28px sans-serif';X.fillStyle='#9fefff';X.fillText('‹',w/2-122,cy+8);X.fillText('›',w/2+122,cy+8);X.font='20px sans-serif';X.fillText('🎲',w/2+182,cy+7);const bw=Math.min(330,pw-80),bh=52,bx=(w-bw)/2,by=y+228;this.hitboxes.start={x:bx,y:by,w:bw,h:bh};X.fillStyle='#72e6d0';X.fillRect(bx,by,bw,bh);X.fillStyle='#102038';X.font='bold 17px sans-serif';X.fillText('开始进化',w/2,by+33);X.fillStyle='#7389b2';X.font='10px sans-serif';X.fillText('左下摇杆移动 · 右下按住冲刺',w/2,y+316)}
  upgrade(){const X=this.ctx,w=this.p.width,h=this.p.height;X.fillStyle='rgba(3,7,20,.76)';X.fillRect(0,0,w,h);X.textAlign='center';X.fillStyle='#fff';X.font='bold 23px sans-serif';X.fillText('选择一个进化 Buff',w/2,46);const gap=14,cw=Math.min(250,(w-56-gap*2)/3),ch=Math.min(230,h-86),startX=(w-(cw*3+gap*2))/2,y=64;this.hitboxes.upgrade=[];for(let i=0;i<3;i++){const b=this.g.choices[i],x=startX+i*(cw+gap);this.hitboxes.upgrade.push({x,y,w:cw,h:ch});this.panel(x,y,cw,ch,.92);X.fillStyle=['#6fffee','#ffd26f','#bf99ff'][i];X.font='bold 13px sans-serif';X.fillText(b.tag,x+cw/2,y+28);X.fillStyle='#fff';X.font='bold 18px sans-serif';X.fillText(b.name,x+cw/2,y+58);X.fillStyle='#9eb0d2';X.font='11px sans-serif';this.wrap(b.desc,x+18,y+88,cw-36,17)}}
  wrap(text,x,y,w,line){const X=this.ctx;let row='',yy=y;for(const ch of text){const t=row+ch;if(X.measureText(t).width>w){X.fillText(row,x+w/2,yy);row=ch;yy+=line}else row=t}if(row)X.fillText(row,x+w/2,yy)}
  gameover(){const X=this.ctx,w=this.p.width,h=this.p.height;X.fillStyle='rgba(3,7,20,.74)';X.fillRect(0,0,w,h);const pw=420,ph=250,x=(w-pw)/2,y=(h-ph)/2;this.panel(x,y,pw,ph,.94);X.textAlign='center';X.fillStyle='#fff';X.font='bold 27px sans-serif';X.fillText('本局结束',w/2,y+52);X.fillStyle='#a9badc';X.font='12px sans-serif';X.fillText('最终长度',w/2,y+82);X.fillStyle='#b9ffec';X.font='bold 45px sans-serif';X.fillText(Math.floor(this.g.player?.score||0),w/2,y+130);X.fillStyle='#91a5ce';X.font='11px sans-serif';X.fillText(`历史最佳 ${this.g.best} · 反杀 ${this.g.player?.kills||0}`,w/2,y+156);const bw=260,bh=48,bx=(w-bw)/2,by=y+180;this.hitboxes.restart={x:bx,y:by,w:bw,h:bh};X.fillStyle='#76ead1';X.fillRect(bx,by,bw,bh);X.fillStyle='#102038';X.font='bold 16px sans-serif';X.fillText('再来一局',w/2,by+31)}
  draw(){this.resize();this.begin();this.hitboxes={};if(this.g.state==='intro'){this.intro();return}this.world();this.hud();this.controls();if(this.g.state==='upgrade')this.upgrade();else if(this.g.state==='gameover')this.gameover()}
}
module.exports={Renderer};